### ISSUE TITLE
grid.appScope is undefined in prepareDraggableRow()

### ISSUE THREAD

**Issue by damiangreen** [cdwv/ui-grid-draggable-rows#14]
grid.appScope is undefined in prepareDraggableRow() on this line:
 return $parse(grid.options.data)(grid.appScope);

My grid looks like so:
 <div id="contentTeaserArticles"
                                 ui-grid="contentTeaserArticlesOptions" class="myGrid"
                                 external-scopes="contentTeaserArticlesExternalScopes"
                                  ui-grid-draggable-rows></div>

**Comment by damiangreen** [comment]
This doesn't occur on the latest version of ui-grid (3.01), so is probably a non-issue

**Comment by skrajewski** [comment]
Thanks you for information!
