### ISSUE TITLE
Issue in IE 11 and firefox

### ISSUE THREAD

**Issue by JonesXavi** [cdwv/ui-grid-draggable-rows#16]
Hi,
I have a a custom text input cell template in my grid, which should be editable with a single click like edit on focus. The editing works perfect in chrome. But the basic editing functionality gets affected in firefox and IE. I couldn't make the pointer point to a particular position of the string in the text box. The action gets blocked. Any idea why its not working in IE 11 and firefox? Thanks in advance.

**Comment by JonesXavi** [comment]
@skrajewski can you help me out in this issue? Its urgent and i couldn't fix it. I can't now revert back and use some other.

**Comment by homerjam** [comment]
So everything is working as expected without the draggable rows directive?

Can you create a demo with the directives/config you're using so I can test it in Firefox please?

Thanks

**Comment by JonesXavi** [comment]
The codepen link that I have shared in my previous comment, show the problem both in firefox and IE. I have set enableCellEditOnFocus: true and included ui-grid-edit in DOM. So, when I try to edit the cell by a double click, I cant place the mouse pointer inside the cell in firefox where as in IE I cant place to a particular position in the cell.

**Comment by homerjam** [comment]
Turns out this is a known bug:

http://stackoverflow.com/questions/21680363/prevent-drag-event-to-interfere-with-input-elements-in-firefox-using-html5-drag
https://bugzilla.mozilla.org/show_bug.cgi?id=800050

Does the edit cell directive emit any events that we can use to disable the `draggable` attribute on blur/focus?

**Comment by homerjam** [comment]
@JonesXavi please can you test #17 ?

**Comment by JonesXavi** [comment]
@homerjam thank you so much. You made my day. It works perfect in both firefox and IE. One more thing I am using a input cell template the below code. So when I use this I'm not able to edit on a single click. Again this single click works as expected without draggable rows directive. So, I thought may be if I'm able to get the event of focusing the particular cell, then I can set "draggable" attribute to false like your fix. Can you please help me out with this?
Codepen link with cellTemplate: http://codepen.io/anon/pen/xGoxXL
                                                         
         <input type="text" class="grid-input" title = "{{row.entity.label}}" ng-model="row.entity.label"/>

**Comment by homerjam** [comment]
I would create a custom directive that changes the draggable attribute of the parent row on focus/blur. If you have jQuery included, something like this (untested):

```js
angular.module('draggableToggle', []).directive('draggableToggle', function() {
    return {
        link: function($scope, $element) {

            $element
            .on('focus', function(e) {
                $(this).closest('.ui-draggable-row').attr('draggable', false);
            })
            .on('blur', function(e) {
                $(this).closest('.ui-draggable-row').attr('draggable', true);
            });

        }
    }
});
```

Then:

```html

<input type="text" draggable-toggle class="grid-input" title="{{row.entity.label}}" ng-model="row.entity.label" />

**Comment by Niranthari** [comment]
hi @homerjam 
when I am using this in my code i have an issue, while i am clicking the cell to edit in grid the scroll bar disappears when there is a large number of rows.could u pls help me out.Thanks in advance.

**Comment by JonesXavi** [comment]
@homerjam Thanks for the custom directive. I had to change a little to make it work in my case.

       app.directive('draggableToggle', function() {
	   return {
		link: function($scope, $element) {
			$element
			.on('focus', function(e) {
				$('.ui-grid-draggable-row').attr('draggable', false);
			})
			.on('blur', function(e) {  
				$('.ui-grid-draggable-row').attr('draggable', true);
			});
		}
	};});

This works perfect. But still when the textbox is focussed for the first time or blurred and focussed again, the same issue(as referred in earlier comments) happens both in firefox and IE .
