### ISSUE TITLE
Firefox issue with drag and drop (dropdowns)

### ISSUE THREAD

**Issue by Saagar-Laxman** [cdwv/ui-grid-draggable-rows#21]
Hi,

Noticed an issue with dropdowns in ui-grid and drag-drop on firefox.

If you open your dropdown and drag an option out of the grid it attempts to redirect you to 'http://move.com'.

The issue is in this line:
e.dataTransfer.setData('Text', 'Move'); // Need to set some data for FF to work 

You still need this workaround but it looks like Firefox recognized 'Text' as a valid key and attempts to create a http redirect to 'Move'.

Changing this to:
e.dataTransfer.setData('foo', 'bar'); // Need to set some data for FF to work   

as an example, resolves the issue.

Thanks for all the work on the plugin btw! Has made life much easier with ui-grid!

Saagar

**Comment by phillipgreenii** [comment]
Is this still an issue?  I haven't been able to duplicate it.

**Comment by skrajewski** [comment]
I cannot reproduce this issue.
