### ISSUE TITLE
ui-grid-draggable-rows thinks my data is just a string

### ISSUE THREAD

**Issue by rhornjr** [cdwv/ui-grid-draggable-rows#24]
This issue was posted on stackoverflow: http://stackoverflow.com/q/33638477/279516

I just followed the directions to get ui-grid-draggable-rows working. They show a working example here.

My issue is that I'm getting this error:
TypeError: this.splice is not a function

At this line of code:
this.splice(to, 0, this.splice(from, 1)[0]);

Just before the splice line, I log this:
console.log(this);

This is the output:
app.Tasks

So it's a string literal. That would explain why splice isn't working. However, that string literal works in my ui-grid to display the tasks. This is in my angular controller:

$scope.gridOptions = {
    data: 'app.Tasks',

So what do I do to get this to work? It seems like a conflict if the draggable plugin treats the data as a literal string, yet the grid uses that literal string to point to the array of data.

Note: In the working example referenced above, they use a hard-coded array of data as the data for the grid. That's obviously okay for an example, but not for real-world use.

**Comment by skrajewski** [comment]
As regards to StackOverflow question, I think this problem was solved.
