### ISSUE TITLE
Item appears disabled after dragging

### ISSUE THREAD

**Issue by susanaseixas** [cdwv/ui-grid-draggable-rows#28]
When I drag an item and leave it on the same spot, it appears disabled (faded). If I leave it on another spot, this also happens but only sometimes (it happens, for example, when I leave it on a spot that appears disabled/faded).

This can be seen on your example: http://codepen.io/anon/pen/wayNOv

**Comment by ricardo85x** [comment]
Same problem here Firefox 44 (Mac OS 10.11 )

On Google Chrome and Safari I do not have this problem.

**Comment by reichert** [comment]
Same problem here: Firefox 44 Windows / Mac
Unfortunatelly I do not have enought knowledge to try to fix this.

**Comment by dneuer** [comment]
Also happens on recent Chrome and IE on Windows.
