### ISSUE TITLE
Row selection does not appear 

### ISSUE THREAD

**Issue by amitkothari** [cdwv/ui-grid-draggable-rows#29]
We have a grid with row selection enabled (enableRowSelection: true). When I use a custom rowTemplate with a draggable wrapper div, the selected row color doesn't change. 

Looking at this issue - https://github.com/angular-ui/ui-grid/issues/3013, it seems like I cannot change the levels of nesting of the divs. Is there a way to make the rows draggable but still keep the selection functionality as it is ?

**Comment by diegofesanto** [comment]
Try add this in the ui-grid.css (inside bower.../angular-ui-grid
`.ui-grid-row.ui-grid-row-selected > [ui-grid-row] > [draggable] > .ui-grid-cell {
  background-color: #c9dde1;
}`

**Comment by amitkothari** [comment]
Thanks @diegofesanto.

Not sure if it is a good idea to change angular-ui-grid css to make it work with the plugin (ui-grid-draggable-rows)

**Comment by diegofesanto** [comment]
I agree with you and I change my comment too. I move the code to my css file and I put after ui-grid-draggable-rows style

Thanks
