### ISSUE TITLE
How to get the row.entity in the draggable-id?

### ISSUE THREAD

**Issue by JonesXavi** [cdwv/ui-grid-draggable-rows#3]
Hi,
Your plugin works perfect. But only thing is that, when I drop the row I need to get the details of the source(which is being dragged) and target(To be dropped postion). How to get those? Plus the below line throws me errorin draggable-id Syntax Error: Token '{' invalid key at column 2 of the expression [{{row.id}}] starting at [{row.id}}]. when included as rowTemplate. Thanks in advance.

       rowTemplate: '<div draggable-id="{{row.id}}" grid="grid" class="ui-grid-draggable-row" draggable="true"><div ng-repeat="(colRenderIndex, col) in colContainer.renderedColumns track by col.colDef.name" class="ui-grid-cell" ng-class="{ \'ui-grid-row-header-cell\': col.isRowHeader, \'custom\': true }" ui-grid-cell></div></div>',

**Comment by skrajewski** [comment]
Hi @JonesXavi ,

thank you for your comment. '{{ row.id }} is one of columns in my table. In `draggagle-id` you should put key/id or something else that will allow you to identify a row. This is only identifier, not special value or plugin functionality :)

Kind regards!

**Comment by JonesXavi** [comment]
@skrajewski  Thanks!
@homerjam Thanks a lot. The fix just made things possible. The issue is solved.
