### ISSUE TITLE
Drag and drop row outside the grid to another HTML element in the page

### ISSUE THREAD

**Issue by vinay07-gl** [cdwv/ui-grid-draggable-rows#36]
Would be useful if we want to drag the row and drop it to some other element, such as another <div>, textArea, Tree, or any other HTML element.
Currently wanted to drag any row to a Tree element present on my page.

**Comment by molecular** [comment]
did you solve this? I could use a solution here, too.

**Comment by vinay07-gl** [comment]
This can't be supported using ui-grid-draggable-rows, as it handles only row related drag and drop, and customizing it won't be a good option.
I solved this by using angular native drag-drop(http://angular-dragdrop.github.io/angular-dragdrop/), which can work in conjunction with ui-grid-draggable-rows. They won't interfere with one another, as the drop would be handled separately.
