### ISSUE TITLE
Row is inserted 1 index too high.

### ISSUE THREAD

**Issue by molecular** [cdwv/ui-grid-draggable-rows#39]
I fixed this by using

```
to -= 1;
```

in the move() function

Am I doing something else wrong?

EDIT: I didn't like this fix because it requires patching of ui-grid-draggable-rows code, see below for a _hack_ I ended up using.

**Comment by molecular** [comment]
might be related to #15

**Comment by molecular** [comment]
I just tried changing the `:before` css rules to `:after` with no effect. The dotted line was still above the row marked `.ui-grid-draggable-row-over`

**Comment by molecular** [comment]
I 'hacked' this by using
    .ui-grid-draggable-row-over:before { top: 22px; }
which is very ugly, of course, because it only works for a certain row height.

**Comment by skrajewski** [comment]
Could you reproduce this issue e.g. in codepen?
