### ISSUE TITLE
Unable to get current target in rowDragged event

### ISSUE THREAD

**Issue by SaurabhBayani** [cdwv/ui-grid-draggable-rows#42]
Hi, Can you please provide some way to that we can get exactly clicked element at time of drag start.  we want to provide drag functionality to only one div of whole row, dragging whole row should not allow user to drag it.

I mean only one element(target element ) should allow dragging, but it should drag whole row

Thanks

**Comment by skrajewski** [comment]
Hi @SaurabhBayani,

sorry, but I didn't get it... Do you want to use one div as "handle" for a whole row? It should be able by using `ui-grid-draggable-row-handle` class together with `$scope.gridOptions.useUiGridDraggableRowsHandle = true;` option. Please see #43.

If you want to _drag and drop_ single cells - it's not possible via this library.

Kind Regards,
Szymon
