### ISSUE TITLE
How do drag handles work?

### ISSUE THREAD

**Issue by AndyKriger** [cdwv/ui-grid-draggable-rows#43]
_To enable using a "handle" for dragging the rows, add the useUiGridDraggableRowsHandle property to your gridOptions and add this class to your handle: ui-grid-draggable-row-handle._

Can you offer some sample code or documentation that shows how the ui-grid-draggable-row-handle class is used in HTML and defined in CSS?

**Comment by skrajewski** [comment]
Hi @AndyKriger,

See at [this codepen](http://codepen.io/skrajewski/pen/JbJpEK). I added a button to each row as a handler. Please note, that this functionality has _hidden dependecy_ from jQuery function `.closest()`. I know it's unexpected behavior and documentation is very poor. 

If you want to improve this functionality or docs, feel free to make the PR.

I hope it will helpful for you.

Kind Regards,
Szymon
