### ISSUE TITLE
Disable draggable and editing cells causes draggable always be true

### ISSUE THREAD

**Issue by elineopsommer** [cdwv/ui-grid-draggable-rows#51]
If you set a callback function to return a value for the 'draggable' attribute, all is fine, but when you start with editing a value in the row f.e. the female character Capitain Marvel, then all the draggable records are enabled instead of disabled.
Visit [codepen](http://codepen.io/anon/pen/gWwmpq)

**Comment by elineopsommer** [comment]
This is caused by this fix https://github.com/cdwv/ui-grid-draggable-rows/pull/17, this cannot be the intention. If the user is ready with editing, the draggable attribute should be it's previous value, so the original function.

**Comment by skrajewski** [comment]
Thanks for report this issue. Fixed in 0.3.3 (see 1ddd922501efd45ff5ae1de2792ee1e9d0c42a3f commit)

Kind regards,
Szymon
