### ISSUE TITLE
Drag and drop across two grids

### ISSUE THREAD

**Issue by gandaldf** [cdwv/ui-grid-draggable-rows#56]
Hi, I've tried to create a simple example of drag and drop across two grids:
https://codepen.io/anon/pen/xrVvNE
It's seems that something is missing, it detect the destination grid (I can see the dotted line) but effectively it can't drop the row in the grid.
Am I doing something wrong?

**Comment by Waszislaw** [comment]
Our package doesn't support this kind of functionality. I'm closing this issue, because of duplication. Please stay tuned, we will work on this feature.

**Comment by Waszislaw** [comment]
#57
