### ISSUE TITLE
Drag handler fails: currentTarget.closest is not a function

### ISSUE THREAD

**Issue by Zergus** [cdwv/ui-grid-draggable-rows#58]
```
Uncaught TypeError: currentTarget.closest is not a function
    at HTMLDivElement.onMouseDownEventListener
```

as `angular.element(e.target)` is jqLite instance and it does not provide `.closest()` method as per [documentation](https://docs.angularjs.org/api/ng/function/angular.element).

**Comment by Zergus** [comment]
https://github.com/cdwv/ui-grid-draggable-rows/pull/59

**Comment by Dzast** [comment]
Hi @Zergus,

For me everything looks good and currentTarget has a function "closest".
Can you tell something more that can helps me to recreate this bug?

**Comment by Zergus** [comment]
Probably you replaced jqLite with jQuery solid, coz according to my case and according to [docs](https://docs.angularjs.org/api/ng/function/angular.element), jqlite does not have `.closest()`.
