### ISSUE TITLE
Replacing ui-grid data breaks toIndex/fromIndex

### ISSUE THREAD

**Issue by TheMarksman** [cdwv/ui-grid-draggable-rows#8]
Hey Szymon, great plugin!

Small issue: 
When the ui-grid data is replaced with another array of data, the indices in the info object do not correspond to the correct indices anymore (indexFrom is always -1). 

This is because the current assumption is that the data does not change after rendering the grid.

**Comment by skrajewski** [comment]
Thank you,

this issue is fixed in 0.2.2 version by #12
