### ISSUE TITLE
a problem with draging rows in Firefox 

### ISSUE THREAD

**Issue by akurg** [cdwv/ui-grid-draggable-rows#9]
FF does not generate the drag event unless e.dataTransfer.setData is set in the dragstart handler.
Also, in dragover handler we need to set the dropEffect property of
dataTransfer to "move", the same as we set effectAllowed in the
dragstart event. If these values didn't match the browser wouldn't let
us drop the item.  
I fixed  it and tested it in my local repo. Here is the diff 
![screen shot 2015-07-16 at 8 50 11 pm](https://cloud.githubusercontent.com/assets/4543475/8738381/7f4226fe-2bfc-11e5-9acb-3940c5a4f3ee.png)
:

**Comment by andrzejwp** [comment]
Hi, can you please open a Pull Request?

**Comment by skrajewski** [comment]
In fact, we solved this issue in fd224b10448c22af98c44b65b1fe0ffc0d2a2068 but during last update to version 0.2 this fix gone.

**Comment by skrajewski** [comment]
Merged #11
